# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('portland', ['core'])
    module.source = [
        'model/portland-fabric-manager.cc',
        'model/portland-switch-net-device.cc',
        'helper/portland-switch-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('portland')
    module_test.source = [
        'test/portland-test-suite.cc',
        ]

    headers = bld.new_task_gen(features=['ns3header'])
    headers.module = 'portland'
    headers.source = [
        'model/portland.h',
	      'model/portland-fabric-manager.h',
        'model/portland-switch-net-device.h',
        'helper/portland-switch-helper.h'
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.add_subdirs('examples')

    # bld.ns3_python_bindings()

