/* -*- Mode:C++; c-file-style:"gnu"; indent-tabs-mode:nil; -*- */
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation;
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * Author: Dhruv Sharma  <dhsharma@cs.ucsd.edu>
 */
#ifndef PORTLAND_INTERFACE_H
#define PORTLAND_INTERFACE_H

#include <assert.h>
#include <errno.h>

// Include OFSI code
#include "ns3/simulator.h"
#include "ns3/log.h"
#include "ns3/net-device.h"
#include "ns3/packet.h"
#include "ns3/address.h"
#include "ns3/nstime.h"
#include "ns3/mac48-address.h"
#include "ns3/ipv4-address.h"
#include "portlandProtocol.h"

#include <set>
#include <map>
#include <limits>

// Include main header
#include "portland/portland.h"

namespace ns3 {

class PortlandSwitchNetDevice;

namespace pld {

/**
 * \brief Port and its metadata.
 *
 * We need to store port metadata, because OpenFlow dictates that there
 * exists a type of request where the Controller asks for data about a
 * port, or multiple ports. Otherwise, we'd refer to it via Ptr<NetDevice>
 * everywhere.
 */
struct Port
{
  Port () : netdev (0),
            rx_packets (0),
            tx_packets (0),
            rx_bytes (0),
            tx_bytes (0),
            tx_dropped (0),
  {
  }

  Ptr<NetDevice> netdev;
  unsigned long long int rx_packets, tx_packets;
  unsigned long long int rx_bytes, tx_bytes;
  unsigned long long int tx_dropped;
};

/**
 * \brief Packet Metadata, allows us to track the packet's metadata as it passes through the switch.
 */
struct SwitchPacketMetadata
{
  uint16_t protocol_number;      ///< Protocol type of the Packet when the Packet is received
  Address src_mac;             ///< Source Address of the Packet when the Packet is received
  Address dst_mac;             ///< Destination Address of the Packet when the Packet is received.
  Ipv4Address src_ip;      ///< Source IPv4 Address of the Packet when the Packet is received
  Ipv4Address dst_ip;      ///< Destination IPv4 Address of the Packet when the Packet is received.
  bool is_arp_request;      ///< True if it is an ARP Request; False otherwise.
};

// Message information for fabric manager
typedef struct BufferData {
    PACKET_TYPE pkt_type; // PACKET_TYPE enum defined in portlandProtocol.h
    void* message; // Need to cast the message based on the packet type
} BufferData;

typedef struct PMACRegister {
    Ipv4Address hostIP;
    Mac48Address PMACAddress;
} PMACRegister;

typedef struct ARPRequest {
    Ipv4Address destIPAddress;
    Ipv4Address srcIPAddress;
    Mac48Address srcPMACAddress;
} ARPRequest;

typedef struct ARPResponse {
	Ipv4Address destIPAddress;
	Ipv4Address destPMACAddress;
	Ipv4Address srcIPAddress;
    Mac48Address srchMACAddress;
} ARPResponse;

typedef struct ARPFloodRequest {
    Ipv4Address destIPAddress;
    Ipv4Address srcIPAddress;
    Mac48Address srcPMACAddress;
} ARPFloodIPAddress;

/**
 * \brief An interface for a FabricManager of PortlandSwitchNetDevices
 *
 * Follows the Portland specification for a fabric manager.
 */
class FabricManager : public Object {
public:
    static TypeId GetTypeId (void);

    ~FabricManager () {
        m_switches.clear ();
        m_learnState.clear ();
    }

  /**
   * Adds a switch to the fabric manager.
   *
   * \param swtch The switch to register.
   */
   virtual void AddSwitch (Ptr<PortlandSwitchNetDevice> swtch);

  /**
   * A switch calls this method to pass a message on to the Fabric Manager.
   *
   * \param swtch The switch the message was received from.
   * \param buffer The message.
   */
    void ReceiveFromSwitch (Ptr<PortlandSwitchNetDevice> swtch, BufferData buffer) {
        PACKET_TYPE packet_type = GetPacketType(buffer);
        switch (packet_type) {
            case PKT_MAC_REGISTER:
                PMACRegister* message = (PMACRegister*) (buffer.message);
                FabricManager_PMACRegisterHandler(message);
                break;

            case PKT_ARP_REQUEST:
                ARPRequest* message = (ARPRequest*) (buffer.message);
                FabricManager_ARPRequestHandler(message, swtch);
                break;

            case PKT_ARP_RESPONSE:
				NS_LOG_COND("PKT_ARP_RESPONSE is to be generated by FM and not consumed");
                break;

            case PKT_ARP_FLOOD: // This is a packet type that the FM should send to core
                NS_LOG_COND("PKT_ARP_FLOOD is to be generated by FM and not consumed");
                break;

            default:
                NS_LOG_COND("Wrong packet type detected : ReceiveFromSwitch Fabric Manager");
                break;
        }
    }

private:

    // IP - PMAC table and management functions
    map<Ipv4Address, Mac48Address> IpPMACTable;
    map<Ipv4Address, Mac48Address>::iterator it;

    void addPMACToTable(Ipv4Address ip, Mac48Address pmac) {
        IpPMACTable[ip] = pmac;
    }

    Ipv4Address getIPforPMAC(Mac48Address pmac) {
        it = IpPMACTable.begin();
        for (it = IpPMACTable.begin(); it != IpPMACTable.end(); ++it) {
            if (it->second == pmac) {
                return it->first;
            }
        }
        return NULL;
    }

    bool isIPRegistered(Ipv4Address ip) {
        it = IpPMACTable.find(ip);
        return (it == IpPMACTable.end() ? false : true);
    }

    Mac48Address getPMACforIP(Ipv4Address ip) {
        if (isIpRegistered(ip)) {
            return IpPMACTable[ip];
        } else {
            return NULL;
        }
    }

    bool isPmacRegistered (string pmac) {
        string ip = getIPforPMAC(pmac);
        return (ip.compare(NULL) == 0 ? false : true);
    }

    // Fabric manager function handlers for packet types
    void FabricManager_PMACRegisterHandler(PMACRegister* message) {
        addPMACToTable(message->hostIP, message->PMACRegister);
    }

    void FabricManager_ARPRequestHandler(ARPRequest* message, Ptr<PortlandSwitchNetDevice> swtch) {
        if (isIpRegistered(message->destIPAddress)) {
            // IP address present
            ARPResponse* msg = (ARPResponse*) malloc (sizeof(ARPResponse));
			msg->srcIPAddress = message->srcIPAddress;
			msg->srcPMACAddress = message->srcPMACAddress;
			msg->destIPAddress = message->destIPAddress;
            msg->destPMACAddress = getPMACforIP(message->destIPAddress);
            FabricManager_ARPResponseHandler(msg, swtch);

			// free the message struct
			free(message);
        } else {
            // Miss in the store, flood it to core
            FabricManager_FloodARPRequest((ARPFloodRequest *)message, swtch);
        }
    }

    void FabricManager_ARPResponseHandler(ARPResponse* message, Ptr<PortlandSwitchNetDevice> swtch) {
		BufferData buffer;
		buffer.pkt_type = PKT_ARP_RESPONSE;
		buffer.msg = message;	
		
        SendToSwitch(swtch, buffer);
    }

    // Packets being generated by the fabric manager
    void FabricManager_FloodARPRequest(ARPFloodRequest* message, swtch, Ptr<PortlandSwitchNetDevice> swtch) {
		BufferData buffer;
		buffer.pkt_type = PKT_ARP_FLOOD;
		buffer.msg = message;

		for (set<Ptr<PortlandSwitchNetDevice>>::iterator it = m_swtiches.begin(); it != m_switches.end(); it++) {
            if (*it->isCore() && *it != swtch) {
                SendToSwitch(*it, buffer);
            }
        }
		// no free
    }

protected:
    Time m_expirationTime;                ///< Time it takes for learned MAC state entry/created flow to expire.
    typedef std::map<Mac48Address, LearnedState> LearnState_t;
    LearnState_t m_learnState;
  /**
   * \internal
   *
   * However the controller is implemented, this method is to
   * be used to pass a message on to a switch.
   *
   * \param swtch The switch to receive the message.
   * \param msg The message to send.
   * \param length The length of the message.
   */
   virtual void SendToSwitch (Ptr<PortlandSwitchNetDevice> swtch, BufferData buffer);

  /**
   * \internal
   *
   * Construct flow data from a matching key to build a flow
   * entry for adding, modifying, or deleting a flow.
   *
   * \param key The matching key data; used to create a flow that matches the packet.
   * \param buffer_id The OpenFlow Buffer ID; used to run the actions on the packet if we add or modify the flow.
   * \param command Whether to add, modify, or delete this flow.
   * \param acts List of actions to execute.
   * \param actions_len Length of the actions buffer.
   * \param idle_timeout Flow expires if left inactive for this amount of time (specify OFP_FLOW_PERMANENT to disable feature).
   * \param hard_timeout Flow expires after this amount of time (specify OFP_FLOW_PERMANENT to disable feature).
   * \return Flow data that when passed to SetFlow will add, modify, or delete a flow it defines.
   */
  ofp_flow_mod* BuildFlow (sw_flow_key key, uint32_t buffer_id, uint16_t command, void* acts, size_t actions_len, int idle_timeout, int hard_timeout);

  /**
   * \internal
   *
   * Get the packet type on the buffer, which can then be used
   * to determine how to handle the buffer.
   *
   * \param buffer The packet in OpenFlow buffer format.
   * \return The packet type, as defined in the ofp_type struct.
   */
    uint8_t GetPacketType (BufferData buffer);

    typedef std::set<Ptr<PortlandSwitchNetDevice> > Switches_t;
    Switches_t m_switches;  ///< The collection of switches registered to this controller.

    struct LearnedState {
        uint32_t port;                      ///< Learned port.
    };
};

/**
 * \brief Executes a list of flow table actions.
 *
 * \param swtch OpenFlowSwitchNetDevice these actions are being executed on.
 * \param packet_uid Packet UID; used to fetch the packet and its metadata.
 * \param buffer The Packet OpenFlow buffer.
 * \param key The matching key for the flow tied to this list of actions.
 * \param actions A buffer of actions.
 * \param actions_len Length of actions buffer.
 * \param ignore_no_fwd If true, during port forwarding actions, ports that are set to not forward are forced to forward.
 */
void ExecuteActions (Ptr<OpenFlowSwitchNetDevice> swtch, uint64_t packet_uid, ofpbuf* buffer, sw_flow_key *key, const ofp_action_header *actions, size_t actions_len, int ignore_no_fwd);

/**
 * \brief Validates a list of flow table actions.
 *
 * \param key The matching key for the flow tied to this list of actions.
 * \param actions A buffer of actions.
 * \param actions_len Length of actions buffer.
 * \return If the action list validates, ACT_VALIDATION_OK is returned. Otherwise, a code for the OFPET_BAD_ACTION error type is returned.
 */
uint16_t ValidateActions (const sw_flow_key *key, const ofp_action_header *actions, size_t actions_len);

}

}

#endif /* PORTLAND_INTERFACE_H */
