FROM python:latest
#FROM ubuntu:latest

#RUN apt-get update
#RUN apt-get install -y python-dev gcc g++ make binutils python-pip
RUN pip install Flask flask-api pymemcache cassandra-driver

#RUN /bin/bash
